---

- name: ensure domains exist
  foreman_domain:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organizations:
    - "{{ organization }}"
    locations: "{{ locations }}"
    name: "{{ item }}"
    validate_certs: "{{ validate_certs }}"
  loop: "{{ domains }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"

