---

- name: ensure domains exist
  foreman_domain:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organizations:
    - "{{ organization }}"
    locations: "{{ locations }}"
    name: "{{ item }}"
  loop: "{{ domains }}"

