---

- hosts: satellite
  vars_files:
  - vars/sat-vars.yml

  tasks:

  - import_role:
      name: sat6-organizations
    tags: organizations

  - import_role:
      name: sat6-locations
    tags: locations

  - import_role:
      name: sat6-manifest
    tags: manifest

  - import_role:
      name: sat6-repositories
    tags: repositories

  - import_role:
      name: sat6-repositories-sync
    tags: repositories-sync

  - import_role:
      name: sat6-lifecycle-environments
    tags: lifecycle-environments

  - import_role:
      name: sat6-content-views
    tags: content-views

  - import_role:
      name: sat6-content-views-publish-and-promote
    tags: publish-and-promote

  - import_role:
      name: sat6-activation-keys
    tags: activation-keys

  - import_role:
      name: sat6-host-groups
    tags: host-groups

  - import_role:
      name: sat6-domains
    tags: domains

  - import_role:
      name: sat6-subnets
    tags: subnets
#
#  - import_role:
#      name: sat6-smart-class-parameters
#    tags: smart-class-parameters
#
#  - import_role:
#      name: sat6-template-sync
#    tags: template-sync
#
#  - import_role:
#      name: sat6-openscap
#    tags: openscap
