---

- name: ensure lifecycle environments exist
  katello_lifecycle_environment:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "https://{{ ansible_nodename }}"
    organization: "{{ organization }}"
    name: "{{ item.name }}"
    label: "{{ item.name }}"
    prior: "{{ item.prior }}"
    state: present
    validate_certs: "{{ validate_certs }}"
  loop: "{{ lifecycle_environments }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"

