---

- name: ensure lifecycle environments exist
  katello_lifecycle_environment:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "https://{{ ansible_nodename }}"
    organization: "{{ organization }}"
    name: "{{ item.name }}"
    label: "{{ item.name }}"
    prior: "{{ item.prior }}"
    state: present
  loop: "{{ lifecycle_environments }}"

