---

- name: ensure host groups exist
  foreman_hostgroup:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    name: "{{ item.name }}"
    architecture: "{{ item.architecture | default(omit) }}"
    compute_profile: "{{ item.compute_profile | default(omit) }}"
    compute_resource: "{{ item.compute_resource | default(omit) }}"
    config_groups: "{{ item.config_groups | default(omit) }}"
    content_source: "{{ item.content_source | default(omit) }}"
    content_view: "{{ item.content_view | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    domain: "{{ item.domain | default(omit) }}"
    environment: "{{ item.environment | default(omit) }}"
    lifecycle_environment: "{{ item.lifecycle_environment | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    medium: "{{ item.medium | default(omit) }}"
    openscap_proxy: "{{ item.openscap_proxy | default(omit) }}"
    operatingsystem: "{{ item.operatingsystem | default(omit) }}"
    parameters: "{{ item.parameters | default(omit) }}"
    parent: "{{ item.parent | default(omit) }}"
    ptable: "{{ item.ptable | default(omit) }}"
    puppet_ca_proxy: "{{ item.puppet_ca_proxy | default(omit) }}"
    puppet_proxy: "{{ item.puppet_proxy | default(omit) }}"
    pxe_loader: "{{ item.pxe_loader | default(omit) }}"
    realm: "{{ item.realm | default(omit) }}"
    root_pass: "{{ item.root_pass | default(omit) }}"
    subnet: "{{ item.subnet | default(omit) }}"
    subnet6: "{{ item.subnet6 | default(omit) }}"
    validate_certs: "{{ validate_certs }}"
  loop: "{{ host_groups }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"
