---

- name: ensure content views exist
  katello_content_view:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    name: "{{ item.name }}"
    repositories: "{{ item.repositories }}"
  loop: "{{ content_views }}"

# TODO: the task below does not work properly. no filters created at this point 

#- name: ensure content view filters exist
#  katello_content_view_filter:
#    username: "{{ username }}"
#    password: "{{ password }}"
#    server_url: "{{ server_url }}"
#    organization: "{{ organization }}"
#    content_view: "{{ item.0.name }}"
#    name: "{{ item.1.name }}"
#    inclusion: "{{ item.1.inclusion }}"
#    filter_type: "{{ item.1.type }}"
#    rule_name: "jq" 
#    repositories:
#    - product: "{{ item.1.product }}"
#      repositories: "{{ item.1.repositories }}"
#  with_subelements:
#  - "{{ content_views }}"
#  - filters
