---

- name: ensure compute resources are present
  command: >
    hammer compute-resource create 
    --name '{{ item.name }}'
    --provider '{{ item.provider }}' 
    --url '{{ item.url }}' 
    --datacenter '{{ item.datacenter }}' 
    --user '{{ item.username }}' 
    --password '{{ item.password }}'
  with_items: "{{ compute_resources }}"
  delegate_to: "{{ 'localhost' if hammer_local else omit }}"
