---

- name: ensure compute resources exist
  foreman_compute_resource:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    validate_certs: "{{ validate_certs }}"
    organizations:
    - "{{ organization }}"
    locations: "{{ locations }}"
    name: "{{ item.name }}"
    provider: "{{ item.provider }}"
    provider_params: "{{ item.provider_params }}"
  loop: "{{ compute_resources }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"
