---

- name: publish a new version of each content view and promote it to all lifecycle environments
  katello_content_view_version:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    content_view: "{{ item.name }}"
    lifecycle_environments: "{{ lifecycle_environments | map(attribute='name') | list }}"
  loop: "{{ content_views }}"
