---

- name: ensure Red Hat repositories are enabled
  katello_repository_set:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    product: "{{ item.0.name }}"
    name: "{{ item.1.name }}"
    state: enabled
    repositories:
    - basearch: "{{ item.1.basearch | default(omit) }}"
      releasever: "{{ item.1.releasever | default(omit) }}"
  with_subelements: 
  - "{{ redhat_products }}"
  - repositories

- name: ensure custom products exist
  katello_product:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    name: "{{ item.name }}"
  loop: "{{ custom_products }}"

- name: ensure directory for GPG keys exist
  file:
    path: '/tmp/gpg-keys'
    state: directory

- name: ensure GPG keys are present
  get_url:
    url: "{{ item.1.gpg_key }}"
    dest: "/tmp/gpg-keys/{{ item.1.gpg_key.split('/')[-1] }}"
  with_subelements:
  - "{{ custom_products }}"
  - repositories

- name: ensure GPG keys exist
  katello_content_credential:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    name: "{{ item.path }}"
    content_type: gpg_key
    content: "{{ lookup('file', '/tmp/gpg-keys/{{ item.path }}') }}"
  with_filetree: /tmp/gpg-keys/

# TODO: ensure global proxy setting is honored

- name: ensure custom repositories exist 
  katello_repository:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    product: "{{ item.0.name }}"
    name: "{{ item.1.name }}"
    content_type: "{{ item.1.content_type }}"
    url: "{{ item.1.url }}"
    download_policy: "{{ download_policy }}"
    gpg_key: "{{ item.1.gpg_key.split('/')[-1] | default(omit) }}"
  with_subelements:
  - "{{ custom_products }}"
  - repositories

