---

# TODO: Can't get this to work. Create manifest as prerequisite for now.

#- name: ensure manifest exist
#  redhat_manifest:
#    name: "{{ ansible_nodename }}"
#    username: "{{ rhsm_username }}"
#    password: "{{ rhsm_password }}"
#    pool_id: xxx
#    quantity: 10
#    path: manifest.zip

- name: copy manifest to remote host
  copy:
     src: "{{ manifest }}"
     dest: "/tmp/manifest.zip"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"

- name: ensure manifest is uploaded
  katello_manifest:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    state: present
    manifest_path: "/tmp/manifest.zip"
    validate_certs: "{{ validate_certs }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"
