---

# TODO: foreman_search_facts does not work with tasks
#
#- name: get all running sync tasks
#  foreman_search_facts:
#    username: "{{ username }}"
#    password: "{{ password }}"
#    server_url: "{{ server_url }}"
#    resource: sync_tasks 
#    search: label = Actions::Katello::Repository::Sync and state = running
#  register: sync_tasks
#
# until issue above is fixed, use hammer to check when syncs are complete

- name: wait for sync tasks to complete
  action: >
    shell hammer
    --csv task list
    --search 'label = Actions::Katello::Repository::Sync and state = running'
  register: running_sync_tasks
  until: running_sync_tasks.stdout.find("running") == -1
  delay: 60
  retries: 600
  changed_when: false
  delegate_to: "{{ 'localhost' if hammer_local else omit }}"


- name: get all repositories
  foreman_search_facts:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    resource: repositories
    validate_certs: "{{ validate_certs }}"
  register: repositories
  delegate_to: "{{ 'localhost' if fam_local else omit }}"

- name: sync of all repositories
  katello_sync:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    product: "{{ item.product.name }}"
    repository:  "{{ item.name }}"
    synchronous: no
    validate_certs: "{{ validate_certs }}"
  loop: "{{ repositories.resources }}"
  when: item.url # repositories without url cannot be synced
  delegate_to: "{{ 'localhost' if fam_local else omit }}"

- name: wait for sync tasks to complete
  action: >
    shell hammer
    --csv task list
    --search 'label = Actions::Katello::Repository::Sync and state = running'
  register: running_sync_tasks
  until: running_sync_tasks.stdout.find("running") == -1
  delay: 60
  retries: 600
  changed_when: false
  delegate_to: "{{ 'localhost' if hammer_local else omit }}"

# TODO: foreman_search_facts does not work with products
#
#- name: get all products
#  foreman_search_facts:
#    username: "{{ username }}"
#    password: "{{ password }}"
#    server_url: "{{ server_url }}"
#    resource: products
#  register: products
#
#  until issue above is fixed, use hammer to get all product names

- name: get all products
  shell: >
    hammer
    --csv product list
    --organization '{{ organization }}'
    --enabled true
    | tail -n +2
    | awk -F ',' '{print $2}'
  register: products
  changed_when: false
  delegate_to: "{{ 'localhost' if hammer_local else omit }}"

- name: ensure sync plan exist
  katello_sync_plan:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ organization }}"
    enabled: yes
    interval: "{{ sync_plan_interval }}"
    name: "{{ sync_plan_name }}"
    sync_date: "{{ lookup('pipe', 'date +\"%Y-%m-%d\" -d \"next day\"') }}"
    products: "{{ products.stdout_lines | list }}"
    validate_certs: "{{ validate_certs }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"
