---

- name: ensure organization {{ organization }} exists
  foreman_organization:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    name: "{{ organization }}"
    validate_certs: "{{ validate_certs }}"
    state: present
  delegate_to: "{{ 'localhost' if fam_local else omit }}"
