---

- name: ensure organization {{ organization }} exists
  foreman_organization:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    name: "{{ organization }}"
    state: present
