---

- name: ensure users exist
  foreman_user:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    validate_certs: "{{ validate_certs }}"
    login: "{{ item.login }}"
    user_password: "{{ item.password }}"
    admin: "{{ item.admin | default(omit) }}"
    firstname: "{{ item.firstname | default(omit) }}"
    lastname: "{{ item.lastname | default(omit) }}"
    mail: "{{ item.mail | default(omit) }}"
    auth_source: "{{ auth_source }}"
    roles: "{{ item.roles }}"
  loop: "{{ users }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"
