---

- name: ensure locations exists
  foreman_location:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    name: "{{ item }}"
    state: present
    organizations:
      - "{{ organization }}"
  loop: "{{ locations }}"
