---

- name: ensure locations exists
  foreman_location:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    name: "{{ item }}"
    state: present
    organizations:
      - "{{ organization }}"
    validate_certs: "{{ validate_certs }}"
  loop: "{{ locations }}"
  delegate_to: "{{ 'localhost' if fam_local else omit }}"
